language: android
sudo: required
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API=25
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=27.0.3
    - ADB_INSTALL_TIMEOUT=5 # minutes
    - EMULATOR_API=25
    - ANDROID_TARGET=android-22
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=21.1.2
    - ANDROID_ABI=google_apis/armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # For Google Maps API v1
    - addon-google_apis-google-$ANDROID_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'
before_script:
  - chmod +x gradlew      #Grand permissions
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./android-sdk-licenses/* "$ANDROID_HOME/licenses/"
  - chmod +x gradlew
  - ./gradlew dependencies || true

script:
  - echo "Building app"
  - android-wait-for-emulator
  - adb devices   #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew clean assemble jacocoTestReport connectedCheck


